site_name: Roberts Lab Handbook
theme:
  name: material
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
repo_url: https://github.com/RobertsLab/resources/
nav:
   - Home: 'index.md'

   - 'Lab Culture':
     - Onboarding: 'Onboarding.md'
     - Code of Conduct: 'Code-of-Conduct.md'
     - Environment and Expectations: 'Environment-and-Expectations.md'
     - Lab Communication: 'Lab-Communication.md'
     - Lab Notebooks: 'Lab-Notebooks.md'
     - DEI Resources: 'DEI-Resources.md'
     - External Communication: 'External-Communication-and-Funding.md'
     - Lab Safety: 'Lab-Safety.md'
     - COVID Plan: 'COVID-Health-and-Safety-Plan.md'
     - Undergraduate Contract: 'Undergraduate-contract.md'

   - 'Computing and Code':
     - Best Practices: 'Computing-Best-Practices.md'
     - Code Snippets: 'code_Snippets.md'
     - Computing Hardware: 'Computing-Hardware.md'
     - Lab Software: 'Lab-Software.md'
     - 'Mox Guides':
       - New User: 'mox_Adding-a-User.md'
       - Logging in: 'mox_Logging-In.md'
       - Node Types: 'mox_Node-Types.md'
       - Data Storage and System Organization: 'mox_Data-Storage-and-System-Organization.md'
       - Running a job: 'mox_Running-a-Job.md'
       - Viewing and interacting with jobs: 'mox_Viewing-and-Interacting-with-Jobs.md'
       - File Transfers: 'mox_File-Transfers.md'
       - Software: 'mox_Software.md'
       - Installing software: 'mox_Installing-Programs.md'
       - Jupyter Notebooks: 'mox_Jupyter-Notebooks.md'
       - RStudio Server: 'mox_RStudio-Server.md'

   - 'Databases and Catalogs':
     - Lab Inventory: 'Lab-Inventory.md'
     - Pubathon: 'Pubathon.md'
     - Digital Media: 'Digital-Media.md'
     - Experiment Database: 'Experiment-Database.md'
     - Genomic Resources: 'Genomic-Resources.md'
     - Spotify Playlists: 'music.md'

   - 'Protocols':
     - Purchasing and Reimbursement: 'Purchasing-and-Reimbursement.md'
     - Data-Management: 'Data-Management.md'
     - Lab Protocols: 'Lab-Protocols.md'
     - Chemical SOPs: 'Chemical-Standard-Operating-Protocols.md'
     - Alarm Information: 'Alarm-Information.md'

   - 'Bioinformatic Workflows':
     - Basics: 'bio_Basics.md'
     - Annotation: 'bio-Annotation.md'
     - DNA Methylation Analysis: 'bio_DNA-methylation.md'
     - Gene Expression: 'bio-Gene-expression.md'
     - Transcriptome Assembly: 'bio_Transcriptome-assembly.md'
