site_name: Roberts Lab Handbook
repo_url: https://github.com/RobertsLab/resources/
edit_uri: blob/master/docs
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
  icon:
    edit: material/pencil
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

nav:
   - Home: 'index.md'

   - 'Lab Culture':
     - Onboarding: 'Onboarding.md'
     - Code of Conduct: 'Code-of-Conduct.md'
     - Environment and Expectations: 'Environment-and-Expectations.md'
     - Lab Communication: 'Lab-Communication.md'
     - Lab Notebooks: 'Lab-Notebooks.md'
     - DEI Resources: 'DEI-Resources.md'
     - External Communication: 'External-Communication-and-Funding.md'
     - Lab Safety: 'Lab-Safety.md'
     - Undergraduate Contract: 'Undergraduate-contract.md'
     - How to Grad School (Outreach Slides): 'How-to-Grad-School-Slides.md'

   - 'Computing and Code':
     - Best Practices: 'Computing-Best-Practices.md'
     - Agentic Coding Tools: 'Agentic-Coding-Tools.md'
     - Code Snippets: 'code_Snippets.md'
     - Computing Hardware: 'Computing-Hardware.md'
     - Lab Software: 'Lab-Software.md'

     - 'Klone Guides':
       - Quick Start: 'klone_quick-start.md'
       - Containers: 'klone_containers.md'
       - Conda: 'klone_Conda.md'
       - New User: 'klone_Adding-a-User.md'
       - Logging in: 'klone_Logging-In.md'
       - Node Types: 'klone_Node-Types.md'
       - Data Storage and System Organization: 'klone_Data-Storage-and-System-Organization.md'
       - Managing Home Directory: 'klone_Managing-Home-Directory.md'
       - File Transfers: 'klone_File-Transfers.md'
       - Installing Programs: 'klone_Installing-Programs.md'
       - Running a job: 'klone_Running-a-Job.md'
       - RStudio Server: 'klone_RStudio-Server.md'
       - VS Code: 'klone_VS-Code.md'
     - 'Raven Guides':
        - Conda: 'raven_Conda.md'
        - RStudio Server: 'raven_RStudio-Server.md'


   - 'Databases and Catalogs':
     - Lab Inventory: 'Lab-Inventory.md'
     - Pubathon: 'Pubathon.md'
     - Digital Media: 'Digital-Media.md'
     - Experiment Database: 'Experiment-Database.md'
     - Genomic Resources: 'Genomic-Resources.md'
     - Spotify Playlists: 'music.md'

   - 'Protocols':
     - Purchasing and Reimbursement: 'Purchasing-and-Reimbursement.md'
     - Data-Management: 'Data-Management.md'
     - Lab Protocols:
       - Bullet Blender: 'protocols/protocol-bullet_blender.md'
       - Glycogen-Glo Assay: 'protocols/protocol-glycogen-glo-assay.md'
       - qPCR: 'protocols/protocol-qPCR.md'
       - Resazurin Assay: 'protocols/resazurin-assay.md'
       - Reverse Transcription: 'protocols/protocol-reverse_transcription.md'
     - Chemical SOPs: 'Chemical-Standard-Operating-Protocols.md'
     - Alarm Information: 'Alarm-Information.md'

   - 'Bioinformatic Workflows':
     - Basics: 'bio_Basics.md'
     - Annotation: 'bio-Annotation.md'
     - DNA Methylation Analysis: 'bio_DNA-methylation.md'
     - Gene Expression: 'bio-Gene-expression.md'
     - Transcriptome Assembly: 'bio_Transcriptome-assembly.md'
